package(default_visibility = ["//visibility:public"])

filegroup(
    name = "db",
    srcs = ["user_payment_db.json"],
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "user_payment_db.json",
    ],
)